Quidditch-Queue-Handlers/FEC-Project-Atelier

client/src/components/ProductDetails/index.jsx
=> #21 Create Product Details Initial Folder Structure and Component

client/src/compononents/ratingsAndReviews/ProductBreakdown.jsx, client/src/compononents/ratingsAndReviews/RatingBreakdown.jsx, client/src/compononents/ratingsAndReviews/Review.jsx, client/src/compononents/ratingsAndReviews/ReviewsList.jsx, client/src/compononents/ratingsAndReviews/Sorting.jsx, client/src/compononents/ratingsAndReviews/WriteReview.jsx, client/src/compononents/ratingsAndReviews/index.jsx
[M] Create branch with agreed upon folder structure ticket#21
=> [M] Create branch with agreed upon folder structure ticket#21

README.md
Finished fixing the update to the README
=> [S] Update Readme #23

.babelrc, .eslintrc.js, client/src/tests/ProductDetails/pdrender.test.js, client/src/tests/demo.test.js, package-lock.json, package.json
This required an update to the react version for compatibility with the react testing renderer. 
Be sure to update dependencies (npm install) after pulling.
=> [S] Setup testing environment with Jest + React Testing Library (#18)

client/src/App.jsx
imported all components and initialized in App
=> [S] Initialize App component with entry point for each 'widget' Ticket#27

client/src/App.jsx
=> [S] Initialize App component with entry point for each 'widget' (Ticket#27)

client/src/components/QuestionsAndAnswers/AddModal.jsx, client/src/components/QuestionsAndAnswers/AddQuestion.jsx, client/src/components/QuestionsAndAnswers/QAList/QAListItem/AddAnswer.jsx, client/src/components/QuestionsAndAnswers/QAList/QAListItem/AnswerList/AnswerListItem.jsx, client/src/components/QuestionsAndAnswers/QAList/QAListItem/AnswerList/index.jsx, client/src/components/QuestionsAndAnswers/QAList/QAListItem/Helpful.jsx, client/src/components/QuestionsAndAnswers/QAList/QAListItem/index.jsx, client/src/components/QuestionsAndAnswers/QAList/index.jsx, client/src/components/QuestionsAndAnswers/Search.jsx, client/src/components/QuestionsAndAnswers/index.jsx
next step is to play with API calls to then be able to properly set up my handlers and rendering of data. then onto the conditional rendering. also did not update any tests, was going to wait until i implement the conditional rendering to implement the tests non trivially
=> [L] QA: declare all states and event handlers and place/pass them to their proper components (#63)

client/src/components/RatingsAndReviews/ProductBreakdown.jsx, client/src/components/RatingsAndReviews/Review.jsx, client/src/components/RatingsAndReviews/ReviewsList.jsx, client/src/components/RatingsAndReviews/Sorting.jsx, client/src/components/RatingsAndReviews/WriteReview.jsx, client/src/components/RatingsAndReviews/index.jsx
Rough ratings and review skeleton
=> [M] RR: Create Skeleton (Ticket#54)

client/src/components/ProductDetails/ProductGallery/Carousel.jsx, client/src/components/ProductDetails/ProductGallery/Thumbnails.jsx, client/src/components/ProductDetails/ProductGallery/index.jsx, client/src/components/ProductDetails/index.jsx, client/src/global.css
Note in global.css I added a --placeholder-color variable matching the provided background color in design schema for image backgrounds.
=> [L] PD: Skeleton Product Gallery Component with Expanding Functionality and Rotating Carousel (#95)

client/src/components/ProductDetails/ProductGallery/Carousel.jsx, client/src/components/ProductDetails/ProductGallery/index.jsx, client/src/components/ProductDetails/ProductInfo.jsx, client/src/components/ProductDetails/ProductStyleSelector/index.jsx, client/src/global.css
Fixes errors from merged branches.
=> [S] PD: Fix image CSS style conflicts on merge (#102)

client/src/App.jsx, client/src/components/RatingsAndReviews/Review.jsx, client/src/components/RatingsAndReviews/ReviewsList.jsx, client/src/components/RatingsAndReviews/Sorting.jsx, server/controllers/reviews/index.js, server/router.js
Rough draft of each individual review card
=> [M] RR: Create individual review tile (Ticket#46)

client/src/components/RatingsAndReviews/ProductBreakdown.jsx, client/src/components/RatingsAndReviews/RatingBreakdown.jsx, client/src/components/RatingsAndReviews/Review.jsx, client/src/components/RatingsAndReviews/ReviewsList.jsx, client/src/components/RatingsAndReviews/WriteReview.jsx, client/src/components/RatingsAndReviews/index.jsx, client/src/global.css
Edited css for ratings and reviews and completed list scrollable content that adds 2 reviews at a time
=> [M] RR: Create Reviews List (Ticket#48)

client/examples/QA-examples/exampleAnswer329062.json, client/examples/QA-examples/exampleAnswer329065.json, client/examples/QA-examples/exampleAnswer329066.json, client/examples/QA-examples/exampleAnswer329068.json, client/examples/QA-examples/exampleAnswer329069.json, client/examples/QA-examples/exampleQuestionCall.json
Added in the example files for testing and for use before API setup
=> [M] Play with API/setup dummy data to be used in tests and before API calls are implemented in client (#26)

client/examples/QA-examples/exampleAnswer329065.json, client/src/components/QuestionsAndAnswers/AddModal.jsx, client/src/components/QuestionsAndAnswers/QAList/QAListItem/AnswerList/AnswerListItem.jsx, client/src/components/QuestionsAndAnswers/QAList/QAListItem/AnswerList/index.jsx, client/src/components/QuestionsAndAnswers/QAList/QAListItem/Helpful.jsx, client/src/components/QuestionsAndAnswers/QAList/QAListItem/index.jsx, client/src/components/QuestionsAndAnswers/QAList/index.jsx, client/src/components/QuestionsAndAnswers/index.jsx, package-lock.json, package.json
This one is a bit of a beefy one, and since there is so much overlap with the questions list some of the changes there are included here... added another dependency in the package.json to parse the date so everyone will need to npm install after they pull.
=> [L] QA: Make it so the user can fully  interact with the Answer List (#64)

client/src/components/common/ReviewStars.js, client/src/global.css
@squeakypickles33 you may want to review this. I made it so the star rating could be controlled by passing in an onRatingChange prop.
=> [M] Shared Star Rating Component, displays variable filled stars and selectable input (#35)

client/src/components/ProductDetails/ProductGallery/Thumbnails.jsx, client/src/components/RatingsAndReviews/Review.jsx, client/src/components/RatingsAndReviews/ReviewsList.jsx, client/src/global.css
Quite a bit of small changes. Also got the thumbnail to pop up full screen
=> [M] RR: Create individual review tile ETC: 11/20 (Ticket#46)

client/src/App.jsx, client/src/components/RatingsAndReviews/Review.jsx
bigphotosrc and show modal re added
=> last sort pr fixes

.gitignore, client/examples/Product-examples/exampleProductInfo.json, client/examples/Product-examples/exampleProductStyles.json, client/examples/Product-examples/exampleProducts.json, client/src/components/ProductDetails/ProductGallery/Carousel.jsx, client/src/components/ProductDetails/ProductGallery/Thumbnails.jsx, client/src/components/ProductDetails/shared/ImageThumbnail.jsx, client/src/components/common/ReviewStars.js, client/src/components/common/ReviewStars.jsx, client/src/tests/ProductDetails/pdrender.test.js, client/src/tests/reviewstars.test.js, package-lock.json, package.json
Note change to test script to include coverage and addition of coverage folder to .gitignore. 
Also created example data for easier testing.
=> [L] Product Detail Component Basic Rendering Tests (#114)

client/src/components/RatingsAndReviews/Review.jsx, client/src/components/RatingsAndReviews/Sorting.jsx, client/src/components/RatingsAndReviews/index.jsx, client/src/global.css
main edits to css for continuity including margin and color variables, small edit to sorts label, and body's show more/less fix
=> [S] RR: Fix background color vars and overall margin (#123)

client/src/components/RatingsAndReviews/Review.jsx, client/src/components/RatingsAndReviews/ReviewsList.jsx, client/src/components/RatingsAndReviews/WriteReview.jsx, client/src/components/RatingsAndReviews/index.jsx, client/src/global.css
made css edits. made start on write review skeleton. fixed GET to retrieve all reviews
=> Final push before demo practice

client/src/components/QuestionsAndAnswers/index.jsx
quick adjustments specifically for the product demo
=> [S] QA: quick adjustments for the product demo (#127)

client/src/components/QuestionsAndAnswers/AddModal.jsx, client/src/components/QuestionsAndAnswers/QAList/QAListItem/AnswerList/index.jsx, client/src/components/QuestionsAndAnswers/QAList/QAListItem/index.jsx, client/src/components/QuestionsAndAnswers/QAList/index.jsx, client/src/components/QuestionsAndAnswers/Search.jsx, client/src/components/QuestionsAndAnswers/index.jsx
depending on the product id I can say that this reduces the total number of axios calls by some ridiculous amount. (this is just a note for me...)
=> [M] QA: Refactor AnswerList component to not use axios calls, and instead sort the lists in the parent. (#129)
